### PR TITLE
Add outline of episode contents

### PR DESCRIPTION
**Pull request by cc-a**
Not nearly as far along as I hoped by now but I've finally settled on a structure that I like so interested on thoughts on that. Ideally I'll do the bits of dialogue up as an image or something.

### CODE REVIEW

**Review by dandavies99 — COMMENTED** [review]
Looks good to me so far!

I reckon your Developer 1 / Developer 2 dialogues are crying out for an xkcd style image, e.g. 

image

(from http://cmx.io/)

In my mind, two similar, common situations are (possibly covered in Differing Goals and Objectives): 
1. Two developers with differing objectives working on totally separate areas of the code at the same time. Two branches that eventually merge with no problems. This is fine. 
2. Two developers with differing objectives working on overlapping areas of the code at the same time. Two branches that eventually have merge conflicts to be resolved. This is also fine because of how git lets you deal with merge conflicts.

So I think we could highlight that merge conflicts are not a problem and not something to necessarily always be avoided. Resolving merge conflicts is something that can be done elegantly and ultimately enables developers to work on code simultaneously without worrying too much about what anyone else is doing.

**Comment by dalonsoa** [comment]
> So I think we could highlight that merge conflicts are not a problem and not something to necessarily always be avoided. Resolving merge conflicts is something that can be done elegantly and ultimately enables developers to work on code simultaneously without worrying too much about what anyone else is doing.

Conflict are dealt with in the old/new branches and merging episode #9 , but I think it is worth to highlight it here in the introduction, too.

**Review by dalonsoa — APPROVED** [review]
Besides Dan's idea of using comic-style dialogs to illustrate the situations, it looks great!

**Comment by dalonsoa** [comment]
@cc-a , will you implement the images in this PR or as separate PRs?

**Comment by cc-a** [comment]
Separate content PR incoming.

**Pull request merged**
